project:
  type: website
  output-dir: docs

website:
  title: "AILO"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Glossary
        href: glossary.qmd
      - text: Posts
        href: posts/index.qmd
    tools:
      - html: inject-toggle.html
  page-footer:
    left: "&copy; 2025 AILO Blog"
    right: "Built with Quarto"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body:
      - inject-toggle.html
    toc: true
    toc-location: right



