project:
  type: website
  output-dir: docs

website:
  title: "AILO Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Posts
        href: posts/index.qmd
    tools:
      - icon: github
        href: https://github.com/aayushgarg/ailo-blog
  page-footer:
    left: "&copy; 2024 AILO Blog"
    right: "Built with Quarto"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body:
      - inject-toggle.html



